// // let total = 0;
// // let bilanganTerbesar = Number.MIN_VALUE;
// // let bilanganTerkecil = Number.MAX_VALUE;

// // for (let i = 1; i <= 20; i++) {
// //     let bilangan = parseFloat(prompt(`Masukkan bilangan ke-${i}:`));

// //     total += bilangan;

// //     if (bilangan > bilanganTerbesar) {
// //         bilanganTerbesar = bilangan;
// //     }

// //     if (bilangan < bilanganTerkecil) {
// //         bilanganTerkecil = bilangan;
// //     }
// // }

// // let rataRata = total / 20;

// // console.log(`Bilangan Terbesar: ${bilanganTerbesar}`);
// // console.log(`Bilangan Terkecil: ${bilanganTerkecil}`);
// // console.log(`Rata-rata: ${rataRata.toFixed(2)}`);


// ////////////////////////////////////////////////////////////////////////////////////////

// let total = 0;
// let bilanganTerbesar= Number.MIN_VALUE;
// let bilanganTerkecil = Number.MAX_VALUE;
// let jumlahBilangan = 0;

// while (jumlahBilangan < 20) {
//     let bilangan = parseFloat(prompt(`Masukkan bilangan ke-${jumlahBilangan + 1}:`));

//     total += bilangan;

//     if (bilangan > bilanganTerbesar) {
//         bilanganTerbesar = bilangan;
//     }

//     if (bilangan < bilanganTerkecil) {
//         bilanganTerkecil = bilangan;
//     }

//     jumlahBilangan++;
// }

// let rataRata = total / 20;

// console.log(`Bilangan Terbesar: ${bilanganTerbesar}`);
// console.log(`Bilangan Terkecil: ${bilanganTerkecil}`);
// console.log(`Rata-rata: ${rataRata.toFixed(2)}`);

